export const STYLES = {
  dp: "display",
  fx: "flex",
  fd: "flexDirection",
  ai: "alignItems",
  jc: "justifyContent",
  m: "margin",
  mt: "marginTop",
  mr: "marginRight",
  mb: "marginBottom",
  ml: "marginLeft",
  pt: "paddingTop",
  pr: "paddingRight",
  pb: "paddingBottom",
  pl: "paddingLeft",
  p: "padding",
  bd: "border",
  bdw: "borderWidth",
  bdc: "borderColor",
  bdr: "borderRadius",
  t: "top",
  b: "bottom",
  r: "right",
  l: "left",
  w: "width",
  h: "height",
  mxw: "maxWidth",
  mxh: "maxHeight",
  mnw: "minWidth",
  mnh: "minHeight",
  ps: "position",
  g: "gap",
  bg: "backgroundColor",
  zi: "zIndex",
};

export const EXCEPT_STYLES = ["zi"];
