export const STYLES = {
  dp: "display",
  fx: "flex",
  fd: "flexDirection",
  ai: "alignItem",
  jc: "justifyContent",
  m: "margin",
  mt: "marginTop",
  mr: "marginRight",
  mb: "marginBottom",
  ml: "marginLeft",
  pt: "paddingTop",
  pr: "paddingRight",
  pb: "paddingBottom",
  pl: "paddingLeft",
  p: "padding",
  bd: "border",
  bdw: "borderWidth",
  bdc: "borderColor",
  bdr: "borderRadius",
  t: "Top",
  b: "Bottom",
  r: "Right",
  l: "Left",
};
